### ISSUE TITLE
County will only show updated after the last round of the map

### ISSUE THREAD

**Issue by SwampyWampyyy** [miraclewhips/geoguessr-userscripts#11]
Basically, when I go to play a US map, the first 4 rounds will not show the county i guessed and the correct one but rather display the last round of the last map i did, like even if im doing a state specific map like texas and before i did a national one it will still display counties that arent even in texas for it

**Comment by miraclewhips** [comment]
try to use violentmonkey extension instead of tampermonkey. i think recent updates to tampermonkey are causing issues.
