### ISSUE TITLE
GM_addStyle is not defined, training mode will not load

### ISSUE THREAD

**Issue by snowe2010** [miraclewhips/geoguessr-userscripts#8]
```
Script error in [Greasemonkey script raw.githubusercontent.com/GeoGuessr Training Mode; version 1.12]:
ReferenceError: GM_addStyle is not defined
```

I can't find any reference to this function in any of your repos either. Where is this coming from? 

Firefox on MacOS Sonoma 14.6.1

**Comment by snowe2010** [comment]
Clearly I'm up too late. Works fine with Tampermonkey, gives the above error with Greasemonkey. Seems that it's a GM only problem (and the `GM_addStyle` comes from Greasemonkey... which I would have realized if I correlated GM with greasemonkey rather than Geoguessr....something).

Maybe a comment on the website or repo stating not to install on Firefox with Greasemonkey?

**Comment by miraclewhips** [comment]
I think the latest versions of Greasemonkey removed support for GM_addStyle for some reason, but the scripts are only tested on Tampermonkey.
