### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mateusext** [miraclewhips/geoguessr-userscripts#9]
Hi! I really like GeoGuessr View Country Leaderboards script but isn't working anymore. Yesterday whenever I clicked in a different country the information were still from my country. Today isn't even showing the box to change the country. I hope you can fix that :)

Thanks a lot!

**Comment by miraclewhips** [comment]
Looks like GeoGuessr updated how the functionality of the leaderboards work. I've managed to get it working again in the latest version of the script, but you need to refresh the page if you change the selected country more than once to force it load the new rankings.
